### ISSUE TITLE
如何实现整体的代码demo

### ISSUE THREAD

**Issue by zhanglaplace** [byangderek/CRAFT#1]
非常感谢提供如此好的开源代码。
想请教下怎么整合四个部分比较好。
另外怎么训练自己的模型。

**Comment by byangderek** [comment]
> 怎么整合四个部分

I think a good way of thinking of this is to combine all four stages in one end-to-end framework like faster-rcnn.
Another interesting idea would be to automatically "learn to cascade", which is to make automatic predictions of whether or not to cascade another network, and what examples/loss would that network has. Something like "deep boosting". 

> 怎么训练自己的模型

The code is basically a combination of official RPN repo and Fast RCNN repo, I would recommend you play with those two projects much to understand logistics like model definition, data flow.
