### ISSUE TITLE
Error in smooth_L1_loss_layer.cpp: Check failed: bottom[0]->channels() == bottom[1]->channels() (2 vs. 1)

### ISSUE THREAD

**Issue by Kaze89** [byangderek/CRAFT#3]
I'm trying to do training in the 4_CasFRCN after the previous 3 steps done.
I used your modified [caffe](https://github.com/byangderek/caffe-fast-rcnn) but found there's no "reshape_layer.cpp" file, so I added it manually from [rbgirshick/caffe-fast-rcnn](https://github.com/rbgirshick/caffe-fast-rcnn/). It worked but when I run train.sh I got another error like this:

```
I0601 17:49:16.684597 31146 layer_factory.hpp:74] Creating layer loss_cls
I0601 17:49:16.684600 31146 net.cpp:84] Creating Layer loss_cls
I0601 17:49:16.684602 31146 net.cpp:380] loss_cls <- cls_score_reshape
I0601 17:49:16.684604 31146 net.cpp:380] loss_cls <- labels_reshape
I0601 17:49:16.684607 31146 net.cpp:380] loss_cls <- cls_loss_weights_reshape
I0601 17:49:16.684610 31146 net.cpp:338] loss_cls -> loss_cls
I0601 17:49:16.684613 31146 net.cpp:113] Setting up loss_cls
F0601 17:49:16.684633 31146 smooth_L1_loss_layer.cpp:22] Check failed: bottom[0]->channels() == bottom[1]->channels() (2 vs. 1) 
*** Check failure stack trace: ***
```

I really appreciate if you can help me, thank you very much!

**Comment by byangderek** [comment]
It looks weird to me because in [train.prototxt](https://github.com/byangderek/CRAFT/blob/master/4_CasFRCN/models/VGG16/train.prototxt) the `bottom[0]` of `smooth_L1_loss` layer is `bbox_pred_80` which is the output of a fc layer, which shouldn't have a `channel_num` of 2.
