### ISSUE TITLE
Where is the test prototxt for detection

### ISSUE THREAD

**Issue by twmht** [byangderek/CRAFT#4]
Hi,

Can you provide the test prototxt  (or the pretrained model) for detecting an image?

for example, in faster rcnn, they provide a single script (https://github.com/rbgirshick/py-faster-rcnn/blob/master/models/pascal_voc/VGG16/faster_rcnn_alt_opt/faster_rcnn_test.pt) to detect an image.

by the way, do I need to include the cascade rpn in test phase?

thanks

**Comment by byangderek** [comment]
Hi,

Unfortunately there's no single script to run all stages, cause this project basically contains four individual repos. 
Following the instructions in readme you should be able to reproduce the model on VOC, and test it on VOC testing images.

**Comment by Huangswust182** [comment]
@twmht Hello, What's in this directory（output/default/voc_2007_trainval/vgg16_fast_rcnn_iter_100000.caffemodel/）? I don't have this path.
